# Dependencies
markdown:         kramdown

# Permalinks
permalink:        /:year/:month/:day/:title/

# Setup
title:            bopjiang
description:      happy coding monkey
url:              http://bopjiang.github.io
email:            bopjiang@163.com
twitter_username: bopjiang
github_username:  bopjiang
github_repo:      https://github.com/bopjiang/bopjiang.github.com

subscribe:        http://bopjiang.github.io/rss.xml
baseurl: ""
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - newpost.rb
  - CNAME

JB :
  comments :
    provider : disqus
    disqus :
      short_name : bopjianggithubio	